# Generated by Django 3.2.9 on 2021-11-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customermodel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customermodel',
            name='phone',
            field=models.CharField(db_column='PHONE', max_length=16, unique=True),
        ),
    ]
